config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('share.urls')),

]

share/urls.py
from django.urls import path

from . import views

app_name = 'share'

urlpatterns = [
    path('', views.LandingPageView.as_view(), name='index'),
    path('add/', views.AddDonationView.as_view(), name='add_donation'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

]

share/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


class Category(models.Model):
    name = models.CharField(max_length=40)

    objects = models.Manager()

    def __str__(self):
        return self.name


class Institution(models.Model):
    name = models.CharField(max_length=40)
    description = models.CharField(max_length=40)
    type = models.CharField(max_length=40, default='foundation', choices=[
        ('foundation', 'Fundacja'),
        ('nongovorg', 'Organizacja pozarządowa'),
        ('local', 'zbiórka lokalna'),
    ])
    categories = models.ManyToManyField('Category')

    objects = models.Manager()

    def __str__(self):
        return self.name


class Donation(models.Model):
    quantity = models.IntegerField()
    categories = models.ManyToManyField('Category')
    institution = models.ForeignKey('Institution', on_delete=models.CASCADE)
    address = models.CharField(max_length=40)
    phone_number = models.IntegerField()
    city = models.CharField(max_length=20)
    zip_code = models.CharField(max_length=20)
    pick_up_date = models.DateField()
    pick_up_time = models.TimeField()
    user = models.ForeignKey('User', on_delete=models.CASCADE)

    objects = models.Manager()

    def __str__(self):
        return f'{self.institution}, {self.quantity}, {self.address}'


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Users require an email field')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

share/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ValidationError

from . import models


class UserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=128, widget=forms.TextInput(attrs={'placeholder': 'Imię'}), label='')
    last_name = forms.CharField(max_length=128, widget=forms.TextInput(attrs={'placeholder': 'Nazwisko'}), label='')
    email = forms.EmailField(max_length=128, widget=forms.EmailInput(attrs={'placeholder': 'Email'}), label='')
    password = forms.CharField(max_length=128, widget=forms.PasswordInput(attrs={'placeholder': 'Hasło'}), label='')
    password_confirmation = forms.CharField(max_length=128, widget=forms.PasswordInput(attrs={'placeholder': 'Powtórz hasło'}),
                                label='')

    class Meta:
        model = models.User
        fields = ('first_name', 'last_name', 'email', 'password', 'password_confirmation')

    def clean_password_confirmation(self):
        password = self.cleaned_data.get('password')
        password_confirmation = self.cleaned_data.get('password_confirmation')

        if password and password_confirmation and password != password_confirmation:
            raise ValidationError('incorrect password')

        return password_confirmation

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get('password'))

        if commit:
            user.save()

        return user


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='', widget=forms.EmailInput(attrs={'placeholder': 'Email'}))
    password = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder': 'Hasło'}))

    class Meta:
        fields = ('email', 'username')

share/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.views import View
from . import models
from django.db.models import Sum
from . import forms


# Create your views here.


class LandingPageView(View):
    def get(self, request):
        donation_quantity = models.Donation.objects.aggregate(Sum('quantity'))['quantity__sum']
        if donation_quantity == None:
            donation_quantity = 0
        supported_organizations = len(models.Donation.objects.values('institution').distinct())

        foundations = models.Institution.objects.filter(type='foundation')
        nongovorgs = models.Institution.objects.filter(type='nongovorg')
        locals = models.Institution.objects.filter(type='local')

        categories = models.Category.objects.all()
        return render(request, 'share/index.html',
                      {'donation_quantity': donation_quantity, 'supported_organizations': supported_organizations,
                       'foundations': foundations, 'nongovorgs': nongovorgs, 'locals': locals,
                       'categories': categories})


class AddDonationView(View):
    def get(self, request):
        return render(request, 'share/form.html')


class LoginView(View):
    def get(self, request):
        form = forms.LoginForm(request)
        return render(request, 'share/login.html', {'form': form})

    def post(self, request):
        form = forms.LoginForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(email=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('share:index')

        return redirect('share:register')


class RegisterView(View):
    def get(self, request):
        form = forms.UserForm()
        return render(request, 'share/register.html', {'form': form})

    def post(self, request):
        form = forms.UserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = True
            user.save()
            return redirect('share:login')

        return render(request, 'share/register.html', {'form': form})


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('share:index')

share/templates/share/form-confirmation.html
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="stylesheet" href="css/style.css" />
  </head>
  <body>
    <header class="header--form-page">
      <nav class="container container--70">
        <ul class="nav--actions">
          <li class="logged-user">
            Witaj Agata
            <ul class="dropdown">
              <li><a href="#">Profil</a></li>
              <li><a href="#">Moje zbiórki</a></li>
              <li><a href="#">Wyloguj</a></li>
            </ul>
          </li>
        </ul>

        <ul>
          <li><a href="index.html" class="btn btn--without-border active">Start</a></li>
          <li><a href="index.html#steps" class="btn btn--without-border">O co chodzi?</a></li>
          <li><a href="index.html#about-us" class="btn btn--without-border">O nas</a></li>
          <li><a href="index.html#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
          <li><a href="index.html#contact" class="btn btn--without-border">Kontakt</a></li>
        </ul>
      </nav>

      <div class="slogan container container--90">
          <h2>
            Dziękujemy za przesłanie formularza Na maila prześlemy wszelkie
            informacje o odbiorze.
          </h2>
      </div>
    </header>

    <footer>
      <div class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
          <div class="form-group form-group--50">
            <input type="text" name="name" placeholder="Imię" />
          </div>
          <div class="form-group form-group--50">
            <input type="text" name="surname" placeholder="Nazwisko" />
          </div>

          <div class="form-group">
            <textarea
              name="message"
              placeholder="Wiadomość"
              rows="1"
            ></textarea>
          </div>

          <button class="btn" type="submit">Wyślij</button>
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2018</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"
            ><img src="images/icon-facebook.svg"
          /></a>
          <a href="#" class="btn btn--small"
            ><img src="images/icon-instagram.svg"
          /></a>
        </div>
      </div>
    </footer>

    <script src="js/app.js"></script>
  </body>
</html>

share/templates/share/form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <body>
    <header class="header--form-page">
      <nav class="container container--70">


            {% include '../partials/_menu.html' %}

      <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Oddaj rzeczy, których już nie chcesz<br />
            <span class="uppercase">potrzebującym</span>
          </h1>

          <div class="slogan--steps">
            <div class="slogan--steps-title">Wystarczą 4 proste kroki:</div>
            <ul class="slogan--steps-boxes">
              <li>
                <div><em>1</em><span>Wybierz rzeczy</span></div>
              </li>
              <li>
                <div><em>2</em><span>Spakuj je w worki</span></div>
              </li>
              <li>
                <div><em>3</em><span>Wybierz fundację</span></div>
              </li>
              <li>
                <div><em>4</em><span>Zamów kuriera</span></div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </header>

    <section class="form--steps">
      <div class="form--steps-instructions">
        <div class="form--steps-container">
          <h3>Ważne!</h3>
          <p data-step="1" class="active">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="2">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="3">
           Wybierz jedną, do
            której trafi Twoja przesyłka.
          </p>
          <p data-step="4">Podaj adres oraz termin odbioru rzeczy.</p>
        </div>
      </div>

      <div class="form--steps-container">
        <div class="form--steps-counter">Krok <span>1</span>/5</div>

        <form action="form-confirmation.html" method="post">
          <!-- STEP 1: class .active is switching steps -->
          <div data-step="1" class="active">
            <h3>Zaznacz co chcesz oddać:</h3>

            <div class="form-group form-group--checkbox">
              <label>
                <input
                  type="checkbox"
                  name="categories"
                  value="clothes-to-use"
                />
                <span class="checkbox"></span>
                <span class="description"
                  >ubrania, które nadają się do ponownego użycia</span
                >
              </label>
            </div>

            <div class="form-group form-group--checkbox">
              <label>
                <input
                  type="checkbox"
                  name="categories"
                  value="clothes-useless"
                />
                <span class="checkbox"></span>
                <span class="description">ubrania, do wyrzucenia</span>
              </label>
            </div>

            <div class="form-group form-group--checkbox">
              <label>
                <input type="checkbox" name="categories" value="toys" />
                <span class="checkbox"></span>
                <span class="description">zabawki</span>
              </label>
            </div>

            <div class="form-group form-group--checkbox">
              <label>
                <input type="checkbox" name="categories" value="books" />
                <span class="checkbox"></span>
                <span class="description">książki</span>
              </label>
            </div>

            <div class="form-group form-group--checkbox">
              <label>
                <input type="checkbox" name="categories" value="other" />
                <span class="checkbox"></span>
                <span class="description">inne</span>
              </label>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 2 -->
          <div data-step="2">
            <h3>Podaj liczbę 60l worków, w które spakowałeś/aś rzeczy:</h3>

            <div class="form-group form-group--inline">
              <label>
                Liczba 60l worków:
                <input type="number" name="bags" step="1" min="1" />
              </label>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>



          <!-- STEP 4 -->
          <div data-step="3">
            <h3>Wybierz organizacje, której chcesz pomóc:</h3>

            <div class="form-group form-group--checkbox">
              <label>
                <input type="radio" name="organization" value="old" />
                <span class="checkbox radio"></span>
                <span class="description">
                  <div class="title">Fundacja “Bez domu”</div>
                  <div class="subtitle">
                    Cel i misja: Pomoc dla osób nie posiadających miejsca
                    zamieszkania
                  </div>
                </span>
              </label>
            </div>

            <div class="form-group form-group--checkbox">
              <label>
                <input type="radio" name="organization" value="old" />
                <span class="checkbox radio"></span>
                <span class="description">
                  <div class="title">Fundacja “Dla dzieci"</div>
                  <div class="subtitle">
                    Cel i misja: Pomoc osobom znajdującym się w trudnej sytuacji
                    życiowej.
                  </div>
                </span>
              </label>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 5 -->
          <div data-step="4">
            <h3>Podaj adres oraz termin odbioru rzecz przez kuriera:</h3>

            <div class="form-section form-section--columns">
              <div class="form-section--column">
                <h4>Adres odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Ulica <input type="text" name="address" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Miasto <input type="text" name="city" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Kod pocztowy <input type="text" name="postcode" />
                  </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Numer telefonu <input type="phone" name="phone" />
                  </label>
                </div>
              </div>

              <div class="form-section--column">
                <h4>Termin odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Data <input type="date" name="data" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Godzina <input type="time" name="time" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Uwagi dla kuriera
                    <textarea name="more_info" rows="5"></textarea>
                  </label>
                </div>
              </div>
            </div>
            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 6 -->
          <div data-step="5">
            <h3>Podsumowanie Twojej darowizny</h3>

            <div class="summary">
              <div class="form-section">
                <h4>Oddajesz:</h4>
                <ul>
                  <li>
                    <span class="icon icon-bag"></span>
                    <span class="summary--text"
                      >4 worki ubrań w dobrym stanie dla dzieci</span
                    >
                  </li>

                  <li>
                    <span class="icon icon-hand"></span>
                    <span class="summary--text"
                      >Dla fundacji "Mam marzenie" w Warszawie</span
                    >
                  </li>
                </ul>
              </div>

              <div class="form-section form-section--columns">
                <div class="form-section--column">
                  <h4>Adres odbioru:</h4>
                  <ul>
                    <li>Prosta 51</li>
                    <li>Warszawa</li>
                    <li>99-098</li>
                    <li>123 456 789</li>
                  </ul>
                </div>

                <div class="form-section--column">
                  <h4>Termin odbioru:</h4>
                  <ul>
                    <li>13/12/2018</li>
                    <li>15:40</li>
                    <li>Brak uwag</li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="submit" class="btn">Potwierdzam</button>
            </div>
          </div>
        </form>
      </div>
    </section>
{% endblock %}

share/templates/share/index.html
{% extends 'base.html' %}


{% block content %}


    <header class="header--main-page">
        <nav class="container container--70">
            {% include '../partials/_menu.html' %}
        </nav>

        <div class="slogan container container--90">
            <div class="slogan--item">
                <h1>
                    Zacznij pomagać!<br/>
                    Oddaj niechciane rzeczy w zaufane ręce
                </h1>
            </div>
        </div>
    </header>

    <body>

    <section id="stats" class="stats">
        <div class="container container--85">
            <div class="stats--item">
                <em>{{ donation_quantity }}</em>
                <h3>Oddanych worków</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius est beatae, quod accusamus illum
                    tempora!</p>
            </div>

            <div class="stats--item">
                <em>{{ supported_organizations }}</em>
                <h3>Wspartych organizacji</h3>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam magnam, sint nihil cupiditate
                    quas
                    quam.</p>
            </div>

        </div>
    </section>

    <section id="steps" class="steps">
        <h2>Wystarczą 4 proste kroki</h2>

        <div class="steps--container">
            <div class="steps--item">
                <span class="icon icon--hands"></span>
                <h3>Wybierz rzeczy</h3>
                <p>ubrania, zabawki, sprzęt i inne</p>
            </div>
            <div class="steps--item">
                <span class="icon icon--arrow"></span>
                <h3>Spakuj je</h3>
                <p>skorzystaj z worków na śmieci</p>
            </div>
            <div class="steps--item">
                <span class="icon icon--glasses"></span>
                <h3>Zdecyduj komu chcesz pomóc</h3>
                <p>wybierz zaufane miejsce</p>
            </div>
            <div class="steps--item">
                <span class="icon icon--courier"></span>
                <h3>Zamów kuriera</h3>
                <p>kurier przyjedzie w dogodnym terminie</p>
            </div>
        </div>

        <a href="{% url 'share:register' %}" class="btn btn--large">Załóż konto</a>
    </section>

    <section id="about-us" class="about-us">
        <div class="about-us--text">
            <h2>O nas</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas vitae animi rem pariatur incidunt
                libero optio
                esse quisquam illo omnis.</p>
            <img src="static/images/signature.svg" class="about-us--text-signature" alt="Signature"/>
        </div>
        <div class="about-us--image"><img src="static/images/about-us.jpg" alt="People in circle"/></div>
    </section>

    <section id="help" class="help">
        <h2>Komu pomagamy?</h2>

        <ul class="help--buttons">
            <li data-id="1"><a href="#" class="btn btn--without-border active">Fundacjom</a></li>
            <li data-id="2"><a href="#" class="btn btn--without-border">Organizacjom pozarządowym</a></li>
            <li data-id="3"><a href="#" class="btn btn--without-border">Lokalnym zbiórkom</a></li>
        </ul>

        <!-- SLIDE 1 -->
        <div class="help--slides active" data-id="1">
            <p>W naszej bazie znajdziesz listę zweryfikowanych Fundacji, z którymi współpracujemy. Możesz sprawdzić czym
                się
                zajmują, komu pomagają i czego potrzebują.</p>

            <ul class="help--slides-items">
                {% for foundation in foundations %}
                    <li>
                        <div class="col">
                            <div class="title">{{ foundation.name }}</div>
                            <div class="subtitle">{{ foundation.description }}</div>
                        </div>

                        <div class="col">
                            <div class="text">{% for category in foundation.categories.all %}{{ category }}, {% endfor %}</div>
                        </div>
                    </li>

                {% endfor %}
            </ul>
            <!-- Pagination
            <ul class="help--slides-pagination">
              <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>
            </ul>
            -->
        </div>


        <!-- SLIDE 2 -->
        <div class="help--slides" data-id="2">
            <p>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic officiis mollitia dolor, neque aspernatur
                accusamus
                debitis. Ducimus, officia. Quia, sunt illum! Non iste placeat ab ipsum alias
                quos suscipit corporis!
            </p>
            <ul class="help--slides-items">
                {% for nongovorg in nongovorgs %}
                    <li>
                        <div class="col">
                            <div class="title">{{ nongovorg.name }}</div>
                            <div class="subtitle">{{ nongovorg.description }}</div>
                        </div>

                        <div class="col">
                            <div class="text">{% for category in nongovorg.categories.all %}{{ category }}{% endfor %}</div>
                        </div>
                    </li>

                {% endfor %}


            </ul>

            <!-- Pagination
            <ul class="help--slides-pagination">
              <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="4">4</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="5">5</a></li>
            </ul>
            -->
        </div>

        <!-- SLIDE 3 -->
        <div class="help--slides" data-id="3">
            <p>Lorem ipsum dolor sit amet, his ocurreret persequeris ea, ad utinam laudem duo. Verterem adipisci
                partiendo eos
                ne, ea his reque quaeque recteque, ne quo lobortis intellegam.</p>
            <ul class="help--slides-items">
                     {% for local in locals %}
                    <li>
                        <div class="col">
                            <div class="title">{{ local.name }}</div>
                            <div class="subtitle">{{ local.description }}</div>
                        </div>

                        <div class="col">
                            <div class="text">{% for category in local.categories.all %}{{ category }}{% endfor %}</div>
                        </div>
                    </li>

                {% endfor %}
            </ul>

            <!-- Pagination
            <ul class="help--slides-pagination">
              <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
            </ul>
            -->
        </div>
    </section>

{% endblock %}
</body>

share/templates/share/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <body>
    <header>
      <nav class="container container--70">
        {% include '../partials/_menu.html' %}
      </nav>
    </header>

    <section class="login-page">
      <h2>Zaloguj się</h2>
            <form action="" method="POST"> {% csrf_token %}
          {% for i in form %}
              <div class="form-group">
          {{ i }}
              </div>
          {% endfor %}
        <div class="form-group">

          <a href="#" class="btn btn--small btn--without-border reset-password">Przypomnij hasło</a>
        </div>

        <div class="form-group form-group--buttons">
          <a href="{% url 'share:register' %}" class="btn btn--without-border">Załóż konto</a>
          <button class="btn" type="submit">Zaloguj się</button>
        </div>
      </form>
    </section>

{% endblock %}

templates/partials/_menu.html
{% if request.path == '/' or request.path == '/add/' %}

{% if user.is_authenticated %}
    <ul class="nav--actions">
        <li class="logged-user">
            Witaj {{ request.user }}
            <ul class="dropdown">
                <li><a href="#">Profil</a></li>
                <li><a href="#">Ustawienia</a></li>
                <li><a href="{% url 'share:logout' %}">Wyloguj</a></li>
            </ul>
        </li>
    </ul>
{% else %}
    <ul class="nav--actions">
        <li><a href="{% url 'share:login' %}" class="btn btn--small btn--without-border">Zaloguj</a></li>
        <li><a href="{% url 'share:register' %}" class="btn btn--small btn--highlighted">Załóż konto</a></li>
    </ul>
{% endif %}
    <ul>
        <li><a href="{% url 'share:index' %}" class="btn btn--without-border active">Start</a></li>
        <li><a href="{% url 'share:index' %}#steps" class="btn btn--without-border">O co chodzi?</a></li>
        <li><a href="{% url 'share:index' %}about-us" class="btn btn--without-border">O nas</a></li>
        <li><a href="{% url 'share:index' %}#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
        <li><a href="{% url 'share:add_donation' %}" class="btn btn--without-border">Przekaż dary</a></li>
        <li><a href="{% url 'share:index' %}#contact" class="btn btn--without-border">Kontakt</a></li>
    </ul>


{% else %}

    <ul class="nav--actions">
        <li><a href="{% url 'share:login' %}">Zaloguj</a></li>
        <li class="highlighted"><a href="{% url 'share:register' %}">Załóż konto</a></li>
    </ul>

    <ul>
        <li><a href="{% url 'share:index' %}">Start</a></li>
        <li><a href="{% url 'share:index' %}#steps">O co chodzi?</a></li>
        <li><a href="{% url 'share:index' %}#about-us">O nas</a></li>
        <li><a href="{% url 'share:index' %}#help">Fundacje i organizacje</a></li>
        <li><a href="{% url 'share:index' %}#contact">Kontakt</a></li>
    </ul>

{% endif %}